import type { ScheduleItem } from './types';

export const defaultScheduleItems: ScheduleItem[] = [
  {
    id: 's-1',
    title: 'Tập luyện buổi sáng',
    type: 'workout',
    startTime: '06:00',
    endTime: '07:00',
    status: 'pending',
    workoutId: 'w-push-1',
  },
  {
    id: 's-2',
    title: 'Nấu bữa sáng',
    type: 'cooking',
    startTime: '07:00',
    endTime: '07:30',
    status: 'pending',
    recipeId: 'r-breakfast-1',
  },
  {
    id: 's-3',
    title: 'Học tập trung',
    type: 'study',
    startTime: '09:00',
    endTime: '11:00',
    status: 'pending',
  },
  {
    id: 's-4',
    title: 'Nghỉ ngắn',
    type: 'rest',
    startTime: '11:00',
    endTime: '11:30',
    status: 'pending',
  },
  {
    id: 's-5',
    title: 'Nấu bữa trưa',
    type: 'cooking',
    startTime: '11:30',
    endTime: '12:15',
    status: 'pending',
    recipeId: 'r-lunch-1',
  },
  {
    id: 's-6',
    title: 'Core chiều',
    type: 'workout',
    startTime: '17:30',
    endTime: '18:15',
    status: 'pending',
    workoutId: 'w-core-1',
  },
  {
    id: 's-7',
    title: 'Nấu bữa tối',
    type: 'cooking',
    startTime: '18:30',
    endTime: '19:15',
    status: 'pending',
    recipeId: 'r-dinner-1',
  },
];
